FROM pdal/pdal:latest

RUN apt-get update && apt-get install -y python3 python3-pip && pip3 install pdal pika requests

COPY src/ /app

WORKDIR /app

CMD ["/opt/conda/envs/pdal/bin/python", "preprocess_worker.py"]